<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Avera.WebApi-3e972538-b63d-4533-a66d-a49f476d6473</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Endpoints\Export\**" />
    <Compile Remove="Endpoints\Profile\**" />
    <Compile Remove="Endpoints\Stats\**" />
    <Compile Remove="Endpoints\Super Admin\**" />
    <Content Remove="Endpoints\Export\**" />
    <Content Remove="Endpoints\Profile\**" />
    <Content Remove="Endpoints\Stats\**" />
    <Content Remove="Endpoints\Super Admin\**" />
    <EmbeddedResource Remove="Endpoints\Export\**" />
    <EmbeddedResource Remove="Endpoints\Profile\**" />
    <EmbeddedResource Remove="Endpoints\Stats\**" />
    <EmbeddedResource Remove="Endpoints\Super Admin\**" />
    <None Remove="Endpoints\Export\**" />
    <None Remove="Endpoints\Profile\**" />
    <None Remove="Endpoints\Stats\**" />
    <None Remove="Endpoints\Super Admin\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dotenv.net" Version="4.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="9.0.14" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Identity.Web" Version="3.0.0" />
    <PackageReference Include="Microsoft.Identity.Web.DownstreamApi" Version="3.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.0" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Endpoints\Cases\" />
    <Folder Include="Endpoints\ML\" />
    <Folder Include="Endpoints\Notifications\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Avera.Application\Avera.Application.csproj" />
    <ProjectReference Include="..\Avera.Infrastructure\Avera.Infrastructure.csproj" />
  </ItemGroup>

</Project>
