<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Identity\TenantSubscription\**" />
    <Compile Remove="Identity\Tenant\**" />
    <EmbeddedResource Remove="Identity\TenantSubscription\**" />
    <EmbeddedResource Remove="Identity\Tenant\**" />
    <None Remove="Identity\TenantSubscription\**" />
    <None Remove="Identity\Tenant\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.15" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Identity\SubscriptionPlans\" />
  </ItemGroup>

  

</Project>
